/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.FormaDePagamentoController;
import fachada.FormaPagamento;
import java.awt.Component;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author miserani
 */
public class JPanelGerenciarFormaPagamento extends javax.swing.JPanel {
    
    int idFormaPagamento;
    int telaTipo;
    JPanelMenuGerenciarDados pai;
    private Component rootPane;
    FormaDePagamentoController formaPagamento = new FormaDePagamentoController();

    /**
     * Creates new form JPanelGerenciarFormaPagamento
     */
    public JPanelGerenciarFormaPagamento(int idFormaPagamento, int tipo, JPanelMenuGerenciarDados pai) {
        initComponents();
        this.pai = pai;
        telaTipo = tipo;
        this.idFormaPagamento = idFormaPagamento;
        if (tipo == 1) {
            formaPagamento.buscarFormaPagamento();
            jButton1.setText("Editar");
            jPanel1.setBorder(BorderFactory.createTitledBorder("Editar Forma de Pagamento"));
            this.formaPagamento.getFormaPagamento(idFormaPagamento);
            this.preencherDadosFormaPagamento(this.formaPagamento.getFormaPagamento());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioVista = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioPrazo = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Forma de Pagamento"));
        jPanel1.setInheritsPopupMenu(true);

        buttonGroup1.add(jRadioVista);
        jRadioVista.setSelected(true);
        jRadioVista.setText("À Vista");

        jLabel5.setText("Tipo de pagamento:");

        jLabel2.setText("Descrição:");

        buttonGroup1.add(jRadioPrazo);
        jRadioPrazo.setText("À Prazo");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioVista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioPrazo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioVista)
                    .addComponent(jRadioPrazo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (telaTipo == 0) {
            
            if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Preencha o campo Descrição");
                
            } else {
                if (jRadioPrazo.isSelected()) {
                    formaPagamento.setFormaPagamento(new FormaPagamento(jTextField1.getText(), 0));
                } else {
                    formaPagamento.setFormaPagamento(new FormaPagamento(jTextField1.getText(), 1));
                }
                this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                jTextField1.setText("");
                JOptionPane.showMessageDialog(rootPane, formaPagamento.cadastrar());
                pai.ativarBotoesFP(telaTipo);
                pai.preencherFormaPagamento();
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                this.setVisible(false);
            }
        } else if (telaTipo == 1) {
            
            if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Preencha o campo Descrição");
                
            } else {
                if (jRadioPrazo.isSelected()) {
                    formaPagamento.setFormaPagamento(new FormaPagamento(jTextField1.getText(), 0));
                } else {
                    formaPagamento.setFormaPagamento(new FormaPagamento(jTextField1.getText(), 1));
                }
                formaPagamento.getFormaPagamento().setIdformaPAgamento(idFormaPagamento);
                this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                jTextField1.setText("");
                JOptionPane.showMessageDialog(rootPane, formaPagamento.editar());
                pai.ativarBotoesFP(telaTipo);
                pai.preencherFormaPagamento();
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pai.ativarBotoesFP(telaTipo);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioPrazo;
    private javax.swing.JRadioButton jRadioVista;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void preencherDadosFormaPagamento(FormaPagamento p) {
        jTextField1.setText(p.getDescricao());
        if (p.getTipoDePagamento() == 0) {
            jRadioPrazo.setSelected(true);
        }
    }
}
